name: Release Please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          release-type: go
          bump-minor-pre-major: true
          pull-request-title-pattern: "release: v${version} [${branch?}]"
      - uses: actions/checkout@v4
      - name: tag major and minor versions
        run: |
          echo ${{ steps.release.outputs.tag_name }}
          echo ${{ steps.release.outputs.minor }}