name: Release Please

on:
  push:
    branches:
      - main
      - 'release/v*'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}

      # Since skip-github-release is specified, the outputs of googleapis/release-please-action cannot be used.
      # Therefore, we need to parse the version manually.
      - name: Extract version from commit message
        if: startsWith(github.event.head_commit.message, 'release:')
        id: extract_version
        shell: bash
        run: |
          echo "version=$( echo "${{ github.event.head_commit.message }}" | sed -n 's/^release: v\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/p' )" >> $GITHUB_OUTPUT

      - name: Tag release
        if: steps.extract_version.outputs.version
        shell: bash
        run: |
          git tag v${{ steps.extract_version.outputs.version }}
          git push origin v${{ steps.extract_version.outputs.version }}
