name: Release Please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
      - name: tag major and minor versions
        run: |
          echo ${{ steps.release.outputs.tag_name }}
          echo ${{ steps.release.outputs.minor }}
      - name: Extract version from commit message
        if: startsWith(github.event.head_commit.message, 'release:') # release-please-action doesn't output the version as it skips GitHub Release.
        id: extract_version
        run: |
          echo "version=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/^release: v\(.*\) \[.*\]$/\1/p')" >> $GITHUB_OUTPUT
      - name: Tag release
        if: steps.extract_version.outputs.version
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.extract_version.outputs.version }}',
              sha: context.sha
            })
